# POST http://localhost:3000/signup
# Content-Type: application/json

# {
#    "fullname":"irfan",
#    "email":"irfanrs024@ai.ai",
#    "password":"irfaN1"



# }



GET http://localhost:3000/get-upload-url
